---
- name: put hdfs-zkfc.rb eye config file
  template: src=hdfs-zkfc.rb dest=/etc/eye/hdfs-zkfc.rb owner=root group=root mode=0644
  when: ansible_os_family != "Elbrus" and (not ("ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('16.04', '>=')"))

- name: load config in eye
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye l /etc/eye/apps.eye"
  become: yes
  when: ansible_os_family != "Elbrus" and (not ("ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('16.04', '>=')"))

- name: put {{ hadoop_distr_prefix }}/bin/zkfc_start.sh
  template: src=zkfc_start.sh dest={{ hadoop_distr_prefix }}/bin/zkfc_start.sh
  when: "ansible_os_family == 'Elbrus'"

- name: chmod {{ hadoop_distr_prefix }}/bin/zkfc_start.sh
  shell: chmod 0755 {{ hadoop_distr_prefix }}/bin/zkfc_start.sh
  when: "ansible_os_family == 'Elbrus'"

- name: check if a port is open
  wait_for: port={{ zookeeper_client_port }} delay=60

- name: check if ZK was formatted
  shell: "{{ zookeeper_distr_prefix }}/bin/zkCli.sh ls /hadoop-ha/{{ hdfs_nameservice_id }}"
  register: result
  ignore_errors: true

- name: print result
  debug: var=result

- name: format a ZK node
  shell: "{{ hadoop_distr_prefix }}-{{ env_name }}-{{ hadoop_version }}/bin/hdfs zkfc -formatZK"
  when: "'does not exist' in result.stderr"
  run_once: true

- name: put systemd unit file to its destination
  template: src=hdfs-zkfc.service dest=/etc/systemd/system/hdfs-zkfc-{{ env_name }}.service owner=root group=root mode=0644
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('16.04', '>=')"
  notify: systemctl daemon-reload

- name: enable hdfs-zkfc service
  service: name=hdfs-zkfc-{{ env_name }} enabled=yes state=started
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('16.04', '>=')"
